// Generated by gencpp from file pkg1/two_ints.msg
// DO NOT EDIT!


#ifndef PKG1_MESSAGE_TWO_INTS_H
#define PKG1_MESSAGE_TWO_INTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg1
{
template <class ContainerAllocator>
struct two_ints_
{
  typedef two_ints_<ContainerAllocator> Type;

  two_ints_()
    : a(0)
    , b(0)  {
    }
  two_ints_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int16_t _a_type;
  _a_type a;

   typedef int16_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::pkg1::two_ints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg1::two_ints_<ContainerAllocator> const> ConstPtr;

}; // struct two_ints_

typedef ::pkg1::two_ints_<std::allocator<void> > two_ints;

typedef boost::shared_ptr< ::pkg1::two_ints > two_intsPtr;
typedef boost::shared_ptr< ::pkg1::two_ints const> two_intsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg1::two_ints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg1::two_ints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg1::two_ints_<ContainerAllocator1> & lhs, const ::pkg1::two_ints_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg1::two_ints_<ContainerAllocator1> & lhs, const ::pkg1::two_ints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg1::two_ints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg1::two_ints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg1::two_ints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg1::two_ints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg1::two_ints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg1::two_ints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg1::two_ints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e01e889cb1a7965611513515df5899bf";
  }

  static const char* value(const ::pkg1::two_ints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe01e889cb1a79656ULL;
  static const uint64_t static_value2 = 0x11513515df5899bfULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg1::two_ints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg1/two_ints";
  }

  static const char* value(const ::pkg1::two_ints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg1::two_ints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 a\n"
"int16 b\n"
;
  }

  static const char* value(const ::pkg1::two_ints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg1::two_ints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct two_ints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg1::two_ints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg1::two_ints_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int16_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG1_MESSAGE_TWO_INTS_H
